# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Publish App"
  inputs:
    command: 'publish'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: "Upload Artifacts"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'dist'

- script: |
    git config --global user.name "Radu Tomuleasa"
    git config --global user.email "radutomy@gmail.com"
    pwd
    ls
    printf "endls\n"
    cd $(Build.ArtifactStagingDirectory)
    pwd
    printf "endpwd\n"
    git init
    ls
#    git checkout -b gh-pages
#    git add -A
#    git commit -m "Created build"
#    git push -f https://0fa5ca5d00c317c5f974bfa4f1f42b5ecd21621a@github.com/radutomy/RealTimeBlazor.git gh-pages
  displayName: 'Publish to GitHub Pages'
  env:
    PAT: $(GitHubPAT)
    NAME: $(GitHubName)
    EMAIL: $(GitHubEmail)
